@startuml
class EDMain
class EDRouteService
class EDRouteServiceFactory
class EDDatasourceFactory
class EDGis
class EDGisCache
class EDInitDatasourceService
class EDGetSystemInfoService
class EDGetAllSystemNamesService
class EDCalcSystemsDistanceService
class EDPathService
class EDBfsAlgo
class EDBulkLoadAlgo
class EDTinyDB
class EDRedis
interface ILogger
interface DatasourceProtocol
interface CacheProtocol

EDMain --> EDRouteService
EDMain --> ILogger
EDRouteServiceFactory --> EDRouteService
EDRouteServiceFactory --> EDDatasourceFactory
EDRouteServiceFactory --> EDGis
EDRouteServiceFactory --> EDGisCache
EDRouteServiceFactory --> EDInitDatasourceService
EDRouteServiceFactory --> EDGetSystemInfoService
EDRouteServiceFactory --> EDGetAllSystemNamesService
EDRouteServiceFactory --> EDCalcSystemsDistanceService
EDRouteServiceFactory --> EDPathService
EDRouteServiceFactory --> EDBfsAlgo
EDRouteServiceFactory --> EDBulkLoadAlgo
EDRouteService --> DatasourceProtocol
EDRouteService --> CacheProtocol
EDDatasourceFactory --> EDTinyDB
EDDatasourceFactory --> EDRedis
@enduml
