@startuml
actor User
participant "main.py" as Main
participant Parser
participant "ed_cli_command_runner.py" as CommandRunner
participant EDMain
participant EDRouteService as RouteService
participant ILogger as Logger

User -> Main: calc_systems_distance --initial --destination
Main -> Parser: parse_args()
Main -> Logger: info("CLI parameters")
Main -> EDMain: create(shared logger)
Main -> CommandRunner: run_command(args, parser, ed_main)
CommandRunner -> Logger: info("CLI command received")
CommandRunner -> EDMain: calc_systems_distance(source, target)
EDMain -> RouteService: calc_systems_distance(source, target)
RouteService --> EDMain: distance
EDMain --> Main: distance
CommandRunner -> Logger: info(distance)
CommandRunner -> Logger: info("Execution time")
@enduml
