@startuml
actor User
participant "main.py" as Main
participant Parser
participant EDMain
participant EDRouteService as RouteService
participant ILogger as Logger

User -> Main: all_loaded_systems
Main -> Parser: parse_args()
Main -> Logger: info("CLI parameters")
Main -> EDMain: create(shared logger)
Main -> Logger: info("CLI command received")
Main -> EDMain: get_all_system_names()
EDMain -> RouteService: get_all_system_names()
RouteService --> EDMain: names
EDMain --> Main: names
Main -> Logger: info("All Loaded Systems")
Main -> Logger: info("Execution time")
@enduml
