@startuml
actor User
participant "main.py" as Main
participant Parser
participant "ed_cli_command_runner.py" as CommandRunner
participant EDMain
participant ILogger as Logger

User -> Main: ping
Main -> Parser: parse_args()
Main -> Logger: info("CLI parameters")
Main -> EDMain: create(shared logger)
Main -> CommandRunner: run_command(args, parser, ed_main)
CommandRunner -> Logger: info("CLI command received: ping")
CommandRunner -> EDMain: ping()
EDMain --> Main: "Pong"
CommandRunner -> Logger: info("Pong")
@enduml
