@startuml
actor User order 10
participant project order 20
participant en_route order 30
participant ed_bfs order 40
participant ed_cache order 50
participant db order 60
participant tinydb order 70
participant edgis order 80
participant edgis_website order 90

User -> project
project -> en_route
en_route -> ed_bfs
ed_bfs -> ed_cache
ed_cache -> db
db ->o tinydb
group query system info
alt system info exists in database
tinydb --> ed_bfs
else system info does not exist in database
ed_cache -> edgis
edgis ->o edgis_website
edgis --> ed_bfs
end
end
group query system neighbors
ed_cache -> db
db ->o tinydb
alt system neighbors exists in database
tinydb --> ed_bfs
else system neighbors does not exist in database
ed_cache -> edgis
edgis ->o edgis_website
edgis --> ed_bfs
end
end
edgis --> en_route
en_route --> project
@enduml
